/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as KinestheticRouteImport } from './routes/kinesthetic'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KinestheticIndexRouteImport } from './routes/kinesthetic.index'
import { Route as KinestheticTeensRouteImport } from './routes/kinesthetic.teens'
import { Route as KinestheticSummaryRouteImport } from './routes/kinesthetic.summary'
import { Route as KinestheticMiddleSchoolRouteImport } from './routes/kinesthetic.middle-school'
import { Route as KinestheticTeensThemeParkRouteImport } from './routes/kinesthetic.teens.theme-park'
import { Route as KinestheticTeensFoodTruckRouteImport } from './routes/kinesthetic.teens.food-truck'
import { Route as KinestheticTeensEscapeRoomRouteImport } from './routes/kinesthetic.teens.escape-room'
import { Route as KinestheticTeensDreamRoomRouteImport } from './routes/kinesthetic.teens.dream-room'
import { Route as KinestheticMiddleSchoolWaterParkRouteImport } from './routes/kinesthetic.middle-school.water-park'
import { Route as KinestheticMiddleSchoolTreehouseRouteImport } from './routes/kinesthetic.middle-school.treehouse'
import { Route as KinestheticMiddleSchoolPetRobotRouteImport } from './routes/kinesthetic.middle-school.pet-robot'
import { Route as KinestheticMiddleSchoolIceCreamRouteImport } from './routes/kinesthetic.middle-school.ice-cream'

const KinestheticRoute = KinestheticRouteImport.update({
  id: '/kinesthetic',
  path: '/kinesthetic',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KinestheticIndexRoute = KinestheticIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KinestheticRoute,
} as any)
const KinestheticTeensRoute = KinestheticTeensRouteImport.update({
  id: '/teens',
  path: '/teens',
  getParentRoute: () => KinestheticRoute,
} as any)
const KinestheticSummaryRoute = KinestheticSummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => KinestheticRoute,
} as any)
const KinestheticMiddleSchoolRoute = KinestheticMiddleSchoolRouteImport.update({
  id: '/middle-school',
  path: '/middle-school',
  getParentRoute: () => KinestheticRoute,
} as any)
const KinestheticTeensThemeParkRoute =
  KinestheticTeensThemeParkRouteImport.update({
    id: '/theme-park',
    path: '/theme-park',
    getParentRoute: () => KinestheticTeensRoute,
  } as any)
const KinestheticTeensFoodTruckRoute =
  KinestheticTeensFoodTruckRouteImport.update({
    id: '/food-truck',
    path: '/food-truck',
    getParentRoute: () => KinestheticTeensRoute,
  } as any)
const KinestheticTeensEscapeRoomRoute =
  KinestheticTeensEscapeRoomRouteImport.update({
    id: '/escape-room',
    path: '/escape-room',
    getParentRoute: () => KinestheticTeensRoute,
  } as any)
const KinestheticTeensDreamRoomRoute =
  KinestheticTeensDreamRoomRouteImport.update({
    id: '/dream-room',
    path: '/dream-room',
    getParentRoute: () => KinestheticTeensRoute,
  } as any)
const KinestheticMiddleSchoolWaterParkRoute =
  KinestheticMiddleSchoolWaterParkRouteImport.update({
    id: '/water-park',
    path: '/water-park',
    getParentRoute: () => KinestheticMiddleSchoolRoute,
  } as any)
const KinestheticMiddleSchoolTreehouseRoute =
  KinestheticMiddleSchoolTreehouseRouteImport.update({
    id: '/treehouse',
    path: '/treehouse',
    getParentRoute: () => KinestheticMiddleSchoolRoute,
  } as any)
const KinestheticMiddleSchoolPetRobotRoute =
  KinestheticMiddleSchoolPetRobotRouteImport.update({
    id: '/pet-robot',
    path: '/pet-robot',
    getParentRoute: () => KinestheticMiddleSchoolRoute,
  } as any)
const KinestheticMiddleSchoolIceCreamRoute =
  KinestheticMiddleSchoolIceCreamRouteImport.update({
    id: '/ice-cream',
    path: '/ice-cream',
    getParentRoute: () => KinestheticMiddleSchoolRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kinesthetic': typeof KinestheticRouteWithChildren
  '/kinesthetic/middle-school': typeof KinestheticMiddleSchoolRouteWithChildren
  '/kinesthetic/summary': typeof KinestheticSummaryRoute
  '/kinesthetic/teens': typeof KinestheticTeensRouteWithChildren
  '/kinesthetic/': typeof KinestheticIndexRoute
  '/kinesthetic/middle-school/ice-cream': typeof KinestheticMiddleSchoolIceCreamRoute
  '/kinesthetic/middle-school/pet-robot': typeof KinestheticMiddleSchoolPetRobotRoute
  '/kinesthetic/middle-school/treehouse': typeof KinestheticMiddleSchoolTreehouseRoute
  '/kinesthetic/middle-school/water-park': typeof KinestheticMiddleSchoolWaterParkRoute
  '/kinesthetic/teens/dream-room': typeof KinestheticTeensDreamRoomRoute
  '/kinesthetic/teens/escape-room': typeof KinestheticTeensEscapeRoomRoute
  '/kinesthetic/teens/food-truck': typeof KinestheticTeensFoodTruckRoute
  '/kinesthetic/teens/theme-park': typeof KinestheticTeensThemeParkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kinesthetic/middle-school': typeof KinestheticMiddleSchoolRouteWithChildren
  '/kinesthetic/summary': typeof KinestheticSummaryRoute
  '/kinesthetic/teens': typeof KinestheticTeensRouteWithChildren
  '/kinesthetic': typeof KinestheticIndexRoute
  '/kinesthetic/middle-school/ice-cream': typeof KinestheticMiddleSchoolIceCreamRoute
  '/kinesthetic/middle-school/pet-robot': typeof KinestheticMiddleSchoolPetRobotRoute
  '/kinesthetic/middle-school/treehouse': typeof KinestheticMiddleSchoolTreehouseRoute
  '/kinesthetic/middle-school/water-park': typeof KinestheticMiddleSchoolWaterParkRoute
  '/kinesthetic/teens/dream-room': typeof KinestheticTeensDreamRoomRoute
  '/kinesthetic/teens/escape-room': typeof KinestheticTeensEscapeRoomRoute
  '/kinesthetic/teens/food-truck': typeof KinestheticTeensFoodTruckRoute
  '/kinesthetic/teens/theme-park': typeof KinestheticTeensThemeParkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kinesthetic': typeof KinestheticRouteWithChildren
  '/kinesthetic/middle-school': typeof KinestheticMiddleSchoolRouteWithChildren
  '/kinesthetic/summary': typeof KinestheticSummaryRoute
  '/kinesthetic/teens': typeof KinestheticTeensRouteWithChildren
  '/kinesthetic/': typeof KinestheticIndexRoute
  '/kinesthetic/middle-school/ice-cream': typeof KinestheticMiddleSchoolIceCreamRoute
  '/kinesthetic/middle-school/pet-robot': typeof KinestheticMiddleSchoolPetRobotRoute
  '/kinesthetic/middle-school/treehouse': typeof KinestheticMiddleSchoolTreehouseRoute
  '/kinesthetic/middle-school/water-park': typeof KinestheticMiddleSchoolWaterParkRoute
  '/kinesthetic/teens/dream-room': typeof KinestheticTeensDreamRoomRoute
  '/kinesthetic/teens/escape-room': typeof KinestheticTeensEscapeRoomRoute
  '/kinesthetic/teens/food-truck': typeof KinestheticTeensFoodTruckRoute
  '/kinesthetic/teens/theme-park': typeof KinestheticTeensThemeParkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/kinesthetic'
    | '/kinesthetic/middle-school'
    | '/kinesthetic/summary'
    | '/kinesthetic/teens'
    | '/kinesthetic/'
    | '/kinesthetic/middle-school/ice-cream'
    | '/kinesthetic/middle-school/pet-robot'
    | '/kinesthetic/middle-school/treehouse'
    | '/kinesthetic/middle-school/water-park'
    | '/kinesthetic/teens/dream-room'
    | '/kinesthetic/teens/escape-room'
    | '/kinesthetic/teens/food-truck'
    | '/kinesthetic/teens/theme-park'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kinesthetic/middle-school'
    | '/kinesthetic/summary'
    | '/kinesthetic/teens'
    | '/kinesthetic'
    | '/kinesthetic/middle-school/ice-cream'
    | '/kinesthetic/middle-school/pet-robot'
    | '/kinesthetic/middle-school/treehouse'
    | '/kinesthetic/middle-school/water-park'
    | '/kinesthetic/teens/dream-room'
    | '/kinesthetic/teens/escape-room'
    | '/kinesthetic/teens/food-truck'
    | '/kinesthetic/teens/theme-park'
  id:
    | '__root__'
    | '/'
    | '/kinesthetic'
    | '/kinesthetic/middle-school'
    | '/kinesthetic/summary'
    | '/kinesthetic/teens'
    | '/kinesthetic/'
    | '/kinesthetic/middle-school/ice-cream'
    | '/kinesthetic/middle-school/pet-robot'
    | '/kinesthetic/middle-school/treehouse'
    | '/kinesthetic/middle-school/water-park'
    | '/kinesthetic/teens/dream-room'
    | '/kinesthetic/teens/escape-room'
    | '/kinesthetic/teens/food-truck'
    | '/kinesthetic/teens/theme-park'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KinestheticRoute: typeof KinestheticRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/kinesthetic': {
      id: '/kinesthetic'
      path: '/kinesthetic'
      fullPath: '/kinesthetic'
      preLoaderRoute: typeof KinestheticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kinesthetic/': {
      id: '/kinesthetic/'
      path: '/'
      fullPath: '/kinesthetic/'
      preLoaderRoute: typeof KinestheticIndexRouteImport
      parentRoute: typeof KinestheticRoute
    }
    '/kinesthetic/teens': {
      id: '/kinesthetic/teens'
      path: '/teens'
      fullPath: '/kinesthetic/teens'
      preLoaderRoute: typeof KinestheticTeensRouteImport
      parentRoute: typeof KinestheticRoute
    }
    '/kinesthetic/summary': {
      id: '/kinesthetic/summary'
      path: '/summary'
      fullPath: '/kinesthetic/summary'
      preLoaderRoute: typeof KinestheticSummaryRouteImport
      parentRoute: typeof KinestheticRoute
    }
    '/kinesthetic/middle-school': {
      id: '/kinesthetic/middle-school'
      path: '/middle-school'
      fullPath: '/kinesthetic/middle-school'
      preLoaderRoute: typeof KinestheticMiddleSchoolRouteImport
      parentRoute: typeof KinestheticRoute
    }
    '/kinesthetic/teens/theme-park': {
      id: '/kinesthetic/teens/theme-park'
      path: '/theme-park'
      fullPath: '/kinesthetic/teens/theme-park'
      preLoaderRoute: typeof KinestheticTeensThemeParkRouteImport
      parentRoute: typeof KinestheticTeensRoute
    }
    '/kinesthetic/teens/food-truck': {
      id: '/kinesthetic/teens/food-truck'
      path: '/food-truck'
      fullPath: '/kinesthetic/teens/food-truck'
      preLoaderRoute: typeof KinestheticTeensFoodTruckRouteImport
      parentRoute: typeof KinestheticTeensRoute
    }
    '/kinesthetic/teens/escape-room': {
      id: '/kinesthetic/teens/escape-room'
      path: '/escape-room'
      fullPath: '/kinesthetic/teens/escape-room'
      preLoaderRoute: typeof KinestheticTeensEscapeRoomRouteImport
      parentRoute: typeof KinestheticTeensRoute
    }
    '/kinesthetic/teens/dream-room': {
      id: '/kinesthetic/teens/dream-room'
      path: '/dream-room'
      fullPath: '/kinesthetic/teens/dream-room'
      preLoaderRoute: typeof KinestheticTeensDreamRoomRouteImport
      parentRoute: typeof KinestheticTeensRoute
    }
    '/kinesthetic/middle-school/water-park': {
      id: '/kinesthetic/middle-school/water-park'
      path: '/water-park'
      fullPath: '/kinesthetic/middle-school/water-park'
      preLoaderRoute: typeof KinestheticMiddleSchoolWaterParkRouteImport
      parentRoute: typeof KinestheticMiddleSchoolRoute
    }
    '/kinesthetic/middle-school/treehouse': {
      id: '/kinesthetic/middle-school/treehouse'
      path: '/treehouse'
      fullPath: '/kinesthetic/middle-school/treehouse'
      preLoaderRoute: typeof KinestheticMiddleSchoolTreehouseRouteImport
      parentRoute: typeof KinestheticMiddleSchoolRoute
    }
    '/kinesthetic/middle-school/pet-robot': {
      id: '/kinesthetic/middle-school/pet-robot'
      path: '/pet-robot'
      fullPath: '/kinesthetic/middle-school/pet-robot'
      preLoaderRoute: typeof KinestheticMiddleSchoolPetRobotRouteImport
      parentRoute: typeof KinestheticMiddleSchoolRoute
    }
    '/kinesthetic/middle-school/ice-cream': {
      id: '/kinesthetic/middle-school/ice-cream'
      path: '/ice-cream'
      fullPath: '/kinesthetic/middle-school/ice-cream'
      preLoaderRoute: typeof KinestheticMiddleSchoolIceCreamRouteImport
      parentRoute: typeof KinestheticMiddleSchoolRoute
    }
  }
}

interface KinestheticMiddleSchoolRouteChildren {
  KinestheticMiddleSchoolIceCreamRoute: typeof KinestheticMiddleSchoolIceCreamRoute
  KinestheticMiddleSchoolPetRobotRoute: typeof KinestheticMiddleSchoolPetRobotRoute
  KinestheticMiddleSchoolTreehouseRoute: typeof KinestheticMiddleSchoolTreehouseRoute
  KinestheticMiddleSchoolWaterParkRoute: typeof KinestheticMiddleSchoolWaterParkRoute
}

const KinestheticMiddleSchoolRouteChildren: KinestheticMiddleSchoolRouteChildren =
  {
    KinestheticMiddleSchoolIceCreamRoute: KinestheticMiddleSchoolIceCreamRoute,
    KinestheticMiddleSchoolPetRobotRoute: KinestheticMiddleSchoolPetRobotRoute,
    KinestheticMiddleSchoolTreehouseRoute:
      KinestheticMiddleSchoolTreehouseRoute,
    KinestheticMiddleSchoolWaterParkRoute:
      KinestheticMiddleSchoolWaterParkRoute,
  }

const KinestheticMiddleSchoolRouteWithChildren =
  KinestheticMiddleSchoolRoute._addFileChildren(
    KinestheticMiddleSchoolRouteChildren,
  )

interface KinestheticTeensRouteChildren {
  KinestheticTeensDreamRoomRoute: typeof KinestheticTeensDreamRoomRoute
  KinestheticTeensEscapeRoomRoute: typeof KinestheticTeensEscapeRoomRoute
  KinestheticTeensFoodTruckRoute: typeof KinestheticTeensFoodTruckRoute
  KinestheticTeensThemeParkRoute: typeof KinestheticTeensThemeParkRoute
}

const KinestheticTeensRouteChildren: KinestheticTeensRouteChildren = {
  KinestheticTeensDreamRoomRoute: KinestheticTeensDreamRoomRoute,
  KinestheticTeensEscapeRoomRoute: KinestheticTeensEscapeRoomRoute,
  KinestheticTeensFoodTruckRoute: KinestheticTeensFoodTruckRoute,
  KinestheticTeensThemeParkRoute: KinestheticTeensThemeParkRoute,
}

const KinestheticTeensRouteWithChildren =
  KinestheticTeensRoute._addFileChildren(KinestheticTeensRouteChildren)

interface KinestheticRouteChildren {
  KinestheticMiddleSchoolRoute: typeof KinestheticMiddleSchoolRouteWithChildren
  KinestheticSummaryRoute: typeof KinestheticSummaryRoute
  KinestheticTeensRoute: typeof KinestheticTeensRouteWithChildren
  KinestheticIndexRoute: typeof KinestheticIndexRoute
}

const KinestheticRouteChildren: KinestheticRouteChildren = {
  KinestheticMiddleSchoolRoute: KinestheticMiddleSchoolRouteWithChildren,
  KinestheticSummaryRoute: KinestheticSummaryRoute,
  KinestheticTeensRoute: KinestheticTeensRouteWithChildren,
  KinestheticIndexRoute: KinestheticIndexRoute,
}

const KinestheticRouteWithChildren = KinestheticRoute._addFileChildren(
  KinestheticRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KinestheticRoute: KinestheticRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
