/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ElementaryIndexRouteImport } from './routes/elementary.index'
import { Route as KinestheticWaterPathRouteImport } from './routes/kinesthetic.water-path'
import { Route as KinestheticResultsRouteImport } from './routes/kinesthetic.results'
import { Route as KinestheticColorLabRouteImport } from './routes/kinesthetic.color-lab'
import { Route as KinestheticBridgeBuilderRouteImport } from './routes/kinesthetic.bridge-builder'
import { Route as ElementaryPuppyMazeRouteImport } from './routes/elementary.puppy-maze'
import { Route as ElementaryPlaygroundRouteImport } from './routes/elementary.playground'
import { Route as ElementaryGardenRouteImport } from './routes/elementary.garden'
import { Route as ElementaryAnimalHouseRouteImport } from './routes/elementary.animal-house'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ElementaryIndexRoute = ElementaryIndexRouteImport.update({
  id: '/elementary/',
  path: '/elementary/',
  getParentRoute: () => rootRouteImport,
} as any)
const KinestheticWaterPathRoute = KinestheticWaterPathRouteImport.update({
  id: '/kinesthetic/water-path',
  path: '/kinesthetic/water-path',
  getParentRoute: () => rootRouteImport,
} as any)
const KinestheticResultsRoute = KinestheticResultsRouteImport.update({
  id: '/kinesthetic/results',
  path: '/kinesthetic/results',
  getParentRoute: () => rootRouteImport,
} as any)
const KinestheticColorLabRoute = KinestheticColorLabRouteImport.update({
  id: '/kinesthetic/color-lab',
  path: '/kinesthetic/color-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const KinestheticBridgeBuilderRoute =
  KinestheticBridgeBuilderRouteImport.update({
    id: '/kinesthetic/bridge-builder',
    path: '/kinesthetic/bridge-builder',
    getParentRoute: () => rootRouteImport,
  } as any)
const ElementaryPuppyMazeRoute = ElementaryPuppyMazeRouteImport.update({
  id: '/elementary/puppy-maze',
  path: '/elementary/puppy-maze',
  getParentRoute: () => rootRouteImport,
} as any)
const ElementaryPlaygroundRoute = ElementaryPlaygroundRouteImport.update({
  id: '/elementary/playground',
  path: '/elementary/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const ElementaryGardenRoute = ElementaryGardenRouteImport.update({
  id: '/elementary/garden',
  path: '/elementary/garden',
  getParentRoute: () => rootRouteImport,
} as any)
const ElementaryAnimalHouseRoute = ElementaryAnimalHouseRouteImport.update({
  id: '/elementary/animal-house',
  path: '/elementary/animal-house',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/elementary/animal-house': typeof ElementaryAnimalHouseRoute
  '/elementary/garden': typeof ElementaryGardenRoute
  '/elementary/playground': typeof ElementaryPlaygroundRoute
  '/elementary/puppy-maze': typeof ElementaryPuppyMazeRoute
  '/kinesthetic/bridge-builder': typeof KinestheticBridgeBuilderRoute
  '/kinesthetic/color-lab': typeof KinestheticColorLabRoute
  '/kinesthetic/results': typeof KinestheticResultsRoute
  '/kinesthetic/water-path': typeof KinestheticWaterPathRoute
  '/elementary/': typeof ElementaryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/elementary/animal-house': typeof ElementaryAnimalHouseRoute
  '/elementary/garden': typeof ElementaryGardenRoute
  '/elementary/playground': typeof ElementaryPlaygroundRoute
  '/elementary/puppy-maze': typeof ElementaryPuppyMazeRoute
  '/kinesthetic/bridge-builder': typeof KinestheticBridgeBuilderRoute
  '/kinesthetic/color-lab': typeof KinestheticColorLabRoute
  '/kinesthetic/results': typeof KinestheticResultsRoute
  '/kinesthetic/water-path': typeof KinestheticWaterPathRoute
  '/elementary': typeof ElementaryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/elementary/animal-house': typeof ElementaryAnimalHouseRoute
  '/elementary/garden': typeof ElementaryGardenRoute
  '/elementary/playground': typeof ElementaryPlaygroundRoute
  '/elementary/puppy-maze': typeof ElementaryPuppyMazeRoute
  '/kinesthetic/bridge-builder': typeof KinestheticBridgeBuilderRoute
  '/kinesthetic/color-lab': typeof KinestheticColorLabRoute
  '/kinesthetic/results': typeof KinestheticResultsRoute
  '/kinesthetic/water-path': typeof KinestheticWaterPathRoute
  '/elementary/': typeof ElementaryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/elementary/animal-house'
    | '/elementary/garden'
    | '/elementary/playground'
    | '/elementary/puppy-maze'
    | '/kinesthetic/bridge-builder'
    | '/kinesthetic/color-lab'
    | '/kinesthetic/results'
    | '/kinesthetic/water-path'
    | '/elementary/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/elementary/animal-house'
    | '/elementary/garden'
    | '/elementary/playground'
    | '/elementary/puppy-maze'
    | '/kinesthetic/bridge-builder'
    | '/kinesthetic/color-lab'
    | '/kinesthetic/results'
    | '/kinesthetic/water-path'
    | '/elementary'
  id:
    | '__root__'
    | '/'
    | '/elementary/animal-house'
    | '/elementary/garden'
    | '/elementary/playground'
    | '/elementary/puppy-maze'
    | '/kinesthetic/bridge-builder'
    | '/kinesthetic/color-lab'
    | '/kinesthetic/results'
    | '/kinesthetic/water-path'
    | '/elementary/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ElementaryAnimalHouseRoute: typeof ElementaryAnimalHouseRoute
  ElementaryGardenRoute: typeof ElementaryGardenRoute
  ElementaryPlaygroundRoute: typeof ElementaryPlaygroundRoute
  ElementaryPuppyMazeRoute: typeof ElementaryPuppyMazeRoute
  KinestheticBridgeBuilderRoute: typeof KinestheticBridgeBuilderRoute
  KinestheticColorLabRoute: typeof KinestheticColorLabRoute
  KinestheticResultsRoute: typeof KinestheticResultsRoute
  KinestheticWaterPathRoute: typeof KinestheticWaterPathRoute
  ElementaryIndexRoute: typeof ElementaryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elementary/': {
      id: '/elementary/'
      path: '/elementary'
      fullPath: '/elementary/'
      preLoaderRoute: typeof ElementaryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kinesthetic/water-path': {
      id: '/kinesthetic/water-path'
      path: '/kinesthetic/water-path'
      fullPath: '/kinesthetic/water-path'
      preLoaderRoute: typeof KinestheticWaterPathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kinesthetic/results': {
      id: '/kinesthetic/results'
      path: '/kinesthetic/results'
      fullPath: '/kinesthetic/results'
      preLoaderRoute: typeof KinestheticResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kinesthetic/color-lab': {
      id: '/kinesthetic/color-lab'
      path: '/kinesthetic/color-lab'
      fullPath: '/kinesthetic/color-lab'
      preLoaderRoute: typeof KinestheticColorLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kinesthetic/bridge-builder': {
      id: '/kinesthetic/bridge-builder'
      path: '/kinesthetic/bridge-builder'
      fullPath: '/kinesthetic/bridge-builder'
      preLoaderRoute: typeof KinestheticBridgeBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elementary/puppy-maze': {
      id: '/elementary/puppy-maze'
      path: '/elementary/puppy-maze'
      fullPath: '/elementary/puppy-maze'
      preLoaderRoute: typeof ElementaryPuppyMazeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elementary/playground': {
      id: '/elementary/playground'
      path: '/elementary/playground'
      fullPath: '/elementary/playground'
      preLoaderRoute: typeof ElementaryPlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elementary/garden': {
      id: '/elementary/garden'
      path: '/elementary/garden'
      fullPath: '/elementary/garden'
      preLoaderRoute: typeof ElementaryGardenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elementary/animal-house': {
      id: '/elementary/animal-house'
      path: '/elementary/animal-house'
      fullPath: '/elementary/animal-house'
      preLoaderRoute: typeof ElementaryAnimalHouseRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ElementaryAnimalHouseRoute: ElementaryAnimalHouseRoute,
  ElementaryGardenRoute: ElementaryGardenRoute,
  ElementaryPlaygroundRoute: ElementaryPlaygroundRoute,
  ElementaryPuppyMazeRoute: ElementaryPuppyMazeRoute,
  KinestheticBridgeBuilderRoute: KinestheticBridgeBuilderRoute,
  KinestheticColorLabRoute: KinestheticColorLabRoute,
  KinestheticResultsRoute: KinestheticResultsRoute,
  KinestheticWaterPathRoute: KinestheticWaterPathRoute,
  ElementaryIndexRoute: ElementaryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
